# Generated by Django 5.2.14 on 2026-05-16 04:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siege_geo', '0005_add_temporal_models_and_plan_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusVintageConfig',
            fields=[
                ('decade', models.IntegerField(help_text='Census decade (1990, 2000, 2010, 2020)', primary_key=True, serialize=False)),
                ('effective_start', models.IntegerField(help_text="First year this vintage's boundaries are used (inclusive)")),
                ('effective_end', models.IntegerField(help_text="Last year this vintage's boundaries are used (inclusive)")),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this vintage has boundaries loaded in the database')),
            ],
            options={
                'verbose_name': 'Census Vintage Configuration',
                'verbose_name_plural': 'Census Vintage Configurations',
                'db_table': 'sw_geo_census_vintage_config',
                'ordering': ['decade'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_number', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('street_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('street_suffix', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('city_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('default_city_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('state_abbreviation', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('zip5', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('delivery_point', models.CharField(blank=True, default=None, max_length=99, null=True)),
                ('delivery_point_check_digit', models.CharField(blank=True, default=None, max_length=99, null=True)),
                ('record_type', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('zip_type', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('county_fips', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('county_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('carrier_route', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('congressional_district', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('rdi', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('elot_sequence', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('elot_sort', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True)),
                ('coordinate_license', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('precision', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('time_zone', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('utc_offset', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('geocoded', models.BooleanField(default=False, help_text='Whether address has been geocoded')),
                ('geocode_quality', models.CharField(blank=True, help_text='Quality: Rooftop, Interpolated, Approximate, Zip', max_length=20, null=True)),
                ('geocode_source', models.CharField(blank=True, help_text='Source: Census, Google, Nominatim, SmartyStreets', max_length=50, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('census_year', models.IntegerField(default=2020, help_text='Census year for boundary assignment (2010, 2020)')),
                ('state_geoid', models.CharField(blank=True, max_length=2, null=True)),
                ('county_geoid', models.CharField(blank=True, max_length=5, null=True)),
                ('tract_geoid', models.CharField(blank=True, max_length=11, null=True)),
                ('block_group_geoid', models.CharField(blank=True, max_length=12, null=True)),
                ('block_geoid', models.CharField(blank=True, max_length=15, null=True)),
                ('vtd_geoid', models.CharField(blank=True, max_length=11, null=True)),
                ('cd_geoid', models.CharField(blank=True, max_length=4, null=True)),
                ('sldl_geoid', models.CharField(blank=True, help_text='State Legislative District Lower GEOID (state FIPS + district)', max_length=5, null=True)),
                ('sldu_geoid', models.CharField(blank=True, help_text='State Legislative District Upper GEOID (state FIPS + district)', max_length=5, null=True)),
                ('census_units_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('tiger_first_seen_year', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Earliest TIGER/Line ADDRFEAT vintage in which this address range appears. Approximates when the address was built. Populated by cross-referencing address against multiple TIGER vintage years.', null=True)),
                ('tiger_last_seen_year', models.PositiveSmallIntegerField(blank=True, help_text='Most recent TIGER/Line ADDRFEAT vintage containing this address. If absent from the latest vintage, the address may have been demolished.', null=True)),
                ('first_seen_in_data', models.DateField(blank=True, db_index=True, help_text='Earliest date this address appeared in any data source (FEC filings, voter files, Census). Cross-validates tiger_first_seen_year.', null=True)),
                ('siege_block_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_addresses', to='siege_geo.blockgroup')),
                ('siege_cd', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_addresses', to='siege_geo.congressionaldistrict')),
                ('siege_county', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_addresses', to='siege_geo.county')),
                ('siege_sldl', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_addresses', to='siege_geo.statelegislativelower')),
                ('siege_sldu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_addresses', to='siege_geo.statelegislativeupper')),
                ('siege_state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_addresses', to='siege_geo.state')),
                ('siege_tract', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_addresses', to='siege_geo.tract')),
                ('siege_vtd', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_addresses', to='siege_geo.vtd')),
            ],
            options={
                'db_table': 'sw_geo_address',
            },
        ),
        migrations.CreateModel(
            name='AddressBoundaryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_date', models.DateField(blank=True, db_index=True, help_text='The date this assignment is valid for (resolves plan)', null=True)),
                ('state_geoid', models.CharField(blank=True, max_length=2, null=True)),
                ('county_geoid', models.CharField(blank=True, max_length=5, null=True)),
                ('tract_geoid', models.CharField(blank=True, max_length=11, null=True)),
                ('block_group_geoid', models.CharField(blank=True, max_length=12, null=True)),
                ('block_geoid', models.CharField(blank=True, max_length=15, null=True)),
                ('vtd_geoid', models.CharField(blank=True, max_length=11, null=True)),
                ('cd_geoid', models.CharField(blank=True, max_length=4, null=True)),
                ('sldl_geoid', models.CharField(blank=True, max_length=5, null=True)),
                ('sldu_geoid', models.CharField(blank=True, max_length=5, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_method', models.CharField(choices=[('SPATIAL_JOIN', 'PostGIS spatial join'), ('CENSUS_API', 'Census Geocoder API'), ('NOMINATIM', 'Nominatim + spatial join'), ('FIPS_LOOKUP', 'Direct FIPS code lookup'), ('PLAN_SPATIAL_JOIN', 'PostGIS spatial join against redistricting plan'), ('MANUAL', 'Manual assignment')], default='SPATIAL_JOIN', max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_periods', to='sw_geo.address')),
                ('congressional_term', models.ForeignKey(blank=True, db_constraint=False, help_text='Congressional term context for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.congressionalterm')),
                ('plan_district_cd', models.ForeignKey(blank=True, db_constraint=False, help_text='PlanDistrict for CD if using a redistricting plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_cd_assignments', to='siege_geo.plandistrict')),
                ('plan_district_sldl', models.ForeignKey(blank=True, db_constraint=False, help_text='PlanDistrict for SLDL if using a redistricting plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_sldl_assignments', to='siege_geo.plandistrict')),
                ('plan_district_sldu', models.ForeignKey(blank=True, db_constraint=False, help_text='PlanDistrict for SLDU if using a redistricting plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_sldu_assignments', to='siege_geo.plandistrict')),
                ('redistricting_plan', models.ForeignKey(blank=True, db_constraint=False, help_text='Active redistricting plan (NULL = Census default boundaries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.redistrictingplan')),
                ('siege_cd', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.congressionaldistrict')),
                ('siege_county', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.county')),
                ('siege_sldl', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.statelegislativelower')),
                ('siege_sldu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.statelegislativeupper')),
                ('siege_state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.state')),
                ('siege_tract', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.tract')),
                ('siege_vtd', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_boundary_periods', to='siege_geo.vtd')),
                ('vintage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_assignments', to='sw_geo.censusvintageconfig')),
            ],
            options={
                'verbose_name': 'Address Boundary Period',
                'verbose_name_plural': 'Address Boundary Periods',
                'db_table': 'sw_geo_address_boundary_period',
                'ordering': ['address', '-vintage', '-context_date'],
            },
        ),
        migrations.CreateModel(
            name='CountyCongressionalDistrictIntersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Census year (both county and CD must match)')),
                ('intersection_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
                ('intersection_area_sqm', models.BigIntegerField()),
                ('pct_of_county', models.DecimalField(decimal_places=2, help_text='% of County area that overlaps with CD', max_digits=5)),
                ('pct_of_cd', models.DecimalField(decimal_places=2, help_text='% of CD area that overlaps with County', max_digits=5)),
                ('relationship', models.CharField(choices=[('COUNTY_IN_CD', 'County fully within CD'), ('CD_IN_COUNTY', 'CD fully within county'), ('SPLIT', 'County split between CDs')], max_length=20)),
                ('is_dominant', models.BooleanField(default=False, help_text='True if this CD contains >50% of county')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('siege_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sw_county_intersections', to='siege_geo.congressionaldistrict')),
                ('siege_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sw_cd_intersections', to='siege_geo.county')),
            ],
            options={
                'verbose_name': 'County-CD Intersection',
                'verbose_name_plural': 'County-CD Intersections',
                'db_table': 'sw_geo_intersection_county_cd',
                'ordering': ['siege_county', '-pct_of_county'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalCongressionalDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.CharField(blank=True, default='', max_length=255)),
                ('party', models.CharField(blank=True, default='', max_length=50)),
                ('siege_cd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sw_political', to='siege_geo.congressionaldistrict')),
            ],
            options={
                'db_table': 'sw_political_cd',
            },
        ),
        migrations.CreateModel(
            name='PoliticalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governor', models.CharField(blank=True, default='', max_length=255)),
                ('governor_party', models.CharField(blank=True, default='', max_length=50)),
                ('legislature_upper_seats', models.PositiveSmallIntegerField(default=0)),
                ('legislature_lower_seats', models.PositiveSmallIntegerField(default=0)),
                ('siege_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sw_political', to='siege_geo.state')),
            ],
            options={
                'db_table': 'sw_political_state',
            },
        ),
        migrations.CreateModel(
            name='PoliticalStateLegislativeLower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_representative', models.CharField(blank=True, default='', max_length=255)),
                ('party', models.CharField(blank=True, default='', max_length=50)),
                ('siege_sldl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sw_political', to='siege_geo.statelegislativelower')),
            ],
            options={
                'db_table': 'sw_political_sldl',
            },
        ),
        migrations.CreateModel(
            name='PoliticalStateLegislativeUpper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_senator', models.CharField(blank=True, default='', max_length=255)),
                ('party', models.CharField(blank=True, default='', max_length=50)),
                ('siege_sldu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sw_political', to='siege_geo.statelegislativeupper')),
            ],
            options={
                'db_table': 'sw_political_sldu',
            },
        ),
        migrations.CreateModel(
            name='VTDCongressionalDistrictIntersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('intersection_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
                ('intersection_area_sqm', models.BigIntegerField()),
                ('pct_of_vtd', models.DecimalField(decimal_places=2, help_text='% of VTD in this CD (for proportional attribution)', max_digits=5)),
                ('pct_of_cd', models.DecimalField(decimal_places=2, help_text='% of CD covered by this VTD', max_digits=5)),
                ('is_dominant', models.BooleanField(db_index=True, default=False, help_text='True if >50% of VTD is in this CD')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('siege_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sw_vtd_intersections', to='siege_geo.congressionaldistrict')),
                ('siege_vtd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sw_cd_intersections', to='siege_geo.vtd')),
            ],
            options={
                'verbose_name': 'VTD-CD Intersection',
                'verbose_name_plural': 'VTD-CD Intersections',
                'db_table': 'sw_geo_intersection_vtd_cd',
                'ordering': ['siege_vtd', '-pct_of_vtd'],
            },
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state_abbreviation', 'city_name'], name='sw_geo_addr_state_a_c57eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['county_fips'], name='sw_geo_addr_county__7b8b17_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['congressional_district'], name='sw_geo_addr_congres_67ce92_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['census_year'], name='sw_geo_addr_census__3c689a_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['geocoded'], name='sw_geo_addr_geocode_21cdc9_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state_geoid', 'county_geoid'], name='sw_geo_addr_state_g_e57e85_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['cd_geoid', 'census_year'], name='sw_geo_addr_cd_geoi_f5cab3_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['vtd_geoid', 'census_year'], name='sw_geo_addr_vtd_geo_b6aaea_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['sldl_geoid', 'census_year'], name='sw_geo_addr_sldl_ge_b12272_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['sldu_geoid', 'census_year'], name='sw_geo_addr_sldu_ge_17b20f_idx'),
        ),
        migrations.AddIndex(
            model_name='addressboundaryperiod',
            index=models.Index(fields=['vintage', 'cd_geoid'], name='sw_geo_addr_vintage_2f2253_idx'),
        ),
        migrations.AddIndex(
            model_name='addressboundaryperiod',
            index=models.Index(fields=['vintage', 'state_geoid', 'county_geoid'], name='sw_geo_addr_vintage_02ffb1_idx'),
        ),
        migrations.AddIndex(
            model_name='addressboundaryperiod',
            index=models.Index(fields=['vintage', 'vtd_geoid'], name='sw_geo_addr_vintage_a3e92d_idx'),
        ),
        migrations.AddIndex(
            model_name='addressboundaryperiod',
            index=models.Index(fields=['vintage', 'sldl_geoid'], name='sw_geo_addr_vintage_0478dc_idx'),
        ),
        migrations.AddIndex(
            model_name='addressboundaryperiod',
            index=models.Index(fields=['vintage', 'sldu_geoid'], name='sw_geo_addr_vintage_ea180b_idx'),
        ),
        migrations.AddIndex(
            model_name='addressboundaryperiod',
            index=models.Index(fields=['context_date', 'state_geoid'], name='sw_geo_addr_context_f4b934_idx'),
        ),
        migrations.AddIndex(
            model_name='addressboundaryperiod',
            index=models.Index(fields=['redistricting_plan', 'cd_geoid'], name='sw_geo_addr_redistr_379097_idx'),
        ),
        migrations.AddConstraint(
            model_name='addressboundaryperiod',
            constraint=models.UniqueConstraint(
                fields=('address', 'vintage', 'redistricting_plan'),
                name='uniq_addr_vintage_plan_nulls_eq',
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name='countycongressionaldistrictintersection',
            index=models.Index(fields=['year', 'siege_county'], name='sw_geo_inte_year_9d8afd_idx'),
        ),
        migrations.AddIndex(
            model_name='countycongressionaldistrictintersection',
            index=models.Index(fields=['year', 'siege_cd'], name='sw_geo_inte_year_87437c_idx'),
        ),
        migrations.AddIndex(
            model_name='countycongressionaldistrictintersection',
            index=models.Index(fields=['relationship'], name='sw_geo_inte_relatio_180763_idx'),
        ),
        migrations.AddIndex(
            model_name='countycongressionaldistrictintersection',
            index=models.Index(fields=['is_dominant'], name='sw_geo_inte_is_domi_32ce50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='countycongressionaldistrictintersection',
            unique_together={('siege_county', 'siege_cd', 'year')},
        ),
        migrations.AddIndex(
            model_name='vtdcongressionaldistrictintersection',
            index=models.Index(fields=['year', 'siege_vtd', 'is_dominant'], name='sw_geo_inte_year_7d3902_idx'),
        ),
        migrations.AddIndex(
            model_name='vtdcongressionaldistrictintersection',
            index=models.Index(fields=['year', 'siege_cd'], name='sw_geo_inte_year_26b090_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vtdcongressionaldistrictintersection',
            unique_together={('siege_vtd', 'siege_cd', 'year')},
        ),
    ]
