# Generated by Django 5.2.14 on 2026-05-16 04:36

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimRedistrictingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_year', models.PositiveSmallIntegerField(help_text='Redistricting cycle year (e.g. 2010, 2020, 2030)', unique=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)])),
                ('decennial_census_year', models.PositiveSmallIntegerField(help_text='Corresponding decennial Census year')),
                ('first_election_year', models.PositiveSmallIntegerField(help_text='First general election under this plan')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Redistricting Cycle Dimension',
                'verbose_name_plural': 'Redistricting Cycle Dimensions',
            },
        ),
        migrations.CreateModel(
            name='DimCensusVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(db_index=True, help_text='Census table ID (e.g. B01001)', max_length=20)),
                ('variable_code', models.CharField(db_index=True, help_text='Full variable code (e.g. B01001_001E)', max_length=30)),
                ('label', models.TextField(help_text='Human-readable variable label')),
                ('concept', models.CharField(blank=True, default='', help_text="Broader concept group (e.g. 'SEX BY AGE')", max_length=255)),
                ('variable_type', models.CharField(choices=[('extensive', 'Extensive (counts, totals — can be summed)'), ('intensive', 'Intensive (rates, medians — cannot be summed)')], default='extensive', help_text='Whether this variable can be aggregated by summing', max_length=15)),
                ('dataset', models.CharField(default='acs5', help_text='Census dataset this variable belongs to', max_length=20)),
                ('universe', models.CharField(blank=True, default='', help_text="Statistical universe (e.g. 'Total population')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Census Variable Dimension',
                'verbose_name_plural': 'Census Variable Dimensions',
                'indexes': [models.Index(fields=['table_id'], name='sw_warehous_table_i_15283c_idx')],
                'unique_together': {('variable_code', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='DimGeography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.CharField(db_index=True, help_text="Census GEOID (e.g. '06037' for LA County)", max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('vintage_year', models.PositiveSmallIntegerField(db_index=True, help_text='TIGER/Line vintage year for this boundary shape', validators=[django.core.validators.MinValueValidator(1790), django.core.validators.MaxValueValidator(2100)])),
                ('summary_level', models.CharField(db_index=True, help_text='Geography type (state, county, tract, blockgroup, place, cd, zcta)', max_length=30)),
                ('state_fips', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Boundary geometry (WGS 84) — nullable for lightweight loads', null=True, srid=4326)),
                ('area_land', models.BigIntegerField(blank=True, help_text='Sq meters', null=True)),
                ('area_water', models.BigIntegerField(blank=True, help_text='Sq meters', null=True)),
                ('internal_point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Interior label point', null=True, srid=4326)),
                ('effective_from', models.DateField(blank=True, help_text="Start of this version's validity period", null=True)),
                ('effective_to', models.DateField(blank=True, help_text="End of this version's validity (NULL = current)", null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='True for the latest version of this geography')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent geography for drill-up (tract→county→state)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sw_warehouse.dimgeography')),
            ],
            options={
                'verbose_name': 'Geography Dimension',
                'verbose_name_plural': 'Geography Dimensions',
            },
        ),
        migrations.CreateModel(
            name='DimSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('acs5', 'ACS 5-Year Estimates'), ('acs1', 'ACS 1-Year Estimates'), ('decennial', 'Decennial Census'), ('decennial_pl', 'Decennial PL 94-171')], help_text='Census program type', max_length=20)),
                ('vintage_year', models.PositiveSmallIntegerField(help_text='Publication/release year of this survey')),
                ('period_start', models.DateField(blank=True, help_text='Start of data collection period', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End of data collection period', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Survey Dimension',
                'verbose_name_plural': 'Survey Dimensions',
                'unique_together': {('survey_type', 'vintage_year')},
            },
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField(help_text='The calendar date', unique=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('quarter', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day_of_year', models.PositiveSmallIntegerField()),
                ('is_census_day', models.BooleanField(default=False, help_text='True on April 1 of decennial Census years (2000, 2010, 2020)')),
                ('is_election_day', models.BooleanField(default=False, help_text='True on the first Tuesday after first Monday in November')),
                ('fiscal_year', models.PositiveSmallIntegerField(help_text='Federal fiscal year (Oct-Sep)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Time Dimension',
                'verbose_name_plural': 'Time Dimensions',
                'indexes': [models.Index(fields=['year', 'quarter'], name='sw_warehous_year_e58978_idx'), models.Index(fields=['is_census_day'], name='sw_warehous_is_cens_aa3e9a_idx'), models.Index(fields=['is_election_day'], name='sw_warehous_is_elec_f03a9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactACSEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.FloatField()),
                ('margin_of_error', models.FloatField(blank=True, null=True)),
                ('coefficient_of_variation', models.FloatField(blank=True, null=True)),
                ('reliability', models.CharField(choices=[('high', 'High (CV < 12%)'), ('medium', 'Medium (CV 12-40%)'), ('low', 'Low (CV > 40%)'), ('suppressed', 'Suppressed by Census Bureau')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acs_estimates', to='sw_warehouse.dimgeography')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acs_estimates', to='sw_warehouse.dimsurvey')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acs_estimates', to='sw_warehouse.dimcensusvariable')),
            ],
            options={
                'verbose_name': 'ACS Estimate',
                'db_table': 'sw_fact_acs_estimate',
            },
        ),
        migrations.CreateModel(
            name='FactDecennialCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decennial_counts', to='sw_warehouse.dimgeography')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decennial_counts', to='sw_warehouse.dimsurvey')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decennial_counts', to='sw_warehouse.dimcensusvariable')),
            ],
            options={
                'verbose_name': 'Decennial Count',
                'db_table': 'sw_fact_decennial_count',
            },
        ),
        migrations.CreateModel(
            name='FactElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('president', 'President'), ('senate', 'U.S. Senate'), ('house', 'U.S. House'), ('governor', 'Governor'), ('state_senate', 'State Senate'), ('state_house', 'State House')], max_length=20)),
                ('party', models.CharField(max_length=50)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('votes', models.IntegerField()),
                ('total_votes', models.IntegerField(blank=True, null=True)),
                ('vote_share', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_results', to='sw_warehouse.dimtime')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_results', to='sw_warehouse.dimgeography')),
            ],
            options={
                'verbose_name': 'Election Result',
                'db_table': 'sw_fact_election_result',
            },
        ),
        migrations.CreateModel(
            name='FactPrecinctResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('president', 'President'), ('senate', 'U.S. Senate'), ('house', 'U.S. House'), ('governor', 'Governor'), ('state_senate', 'State Senate'), ('state_house', 'State House'), ('attorney_general', 'Attorney General'), ('secretary_of_state', 'Secretary of State')], max_length=30)),
                ('party', models.CharField(max_length=50)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('votes', models.IntegerField()),
                ('total_votes', models.IntegerField(blank=True, null=True)),
                ('vote_share', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precinct_results', to='sw_warehouse.dimtime')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precinct_results', to='sw_warehouse.dimgeography')),
            ],
            options={
                'verbose_name': 'Precinct Result',
                'db_table': 'sw_fact_precinct_result',
            },
        ),
        migrations.CreateModel(
            name='FactRedistrictingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(choices=[('congress', 'U.S. Congress'), ('state_senate', 'State Senate'), ('state_house', 'State House')], max_length=20)),
                ('plan_type', models.CharField(choices=[('enacted', 'Enacted'), ('proposed', 'Proposed'), ('alternative', 'Alternative'), ('court_ordered', 'Court-Ordered'), ('commission', 'Commission')], default='enacted', max_length=20)),
                ('district_number', models.CharField(max_length=10)),
                ('total_population', models.BigIntegerField(blank=True, null=True)),
                ('vap', models.BigIntegerField(blank=True, help_text='Voting age population', null=True)),
                ('cvap', models.BigIntegerField(blank=True, help_text='Citizen voting age population', null=True)),
                ('deviation_pct', models.FloatField(blank=True, null=True)),
                ('polsby_popper', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reock', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_facts', to='sw_warehouse.dimredistrictingcycle')),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redistricting_plans', to='sw_warehouse.dimgeography')),
            ],
            options={
                'verbose_name': 'Redistricting Plan Fact',
                'db_table': 'sw_fact_redistricting_plan',
            },
        ),
        migrations.CreateModel(
            name='FactUrbanicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nces_year', models.PositiveSmallIntegerField()),
                ('locale_code', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(43)])),
                ('locale_category', models.CharField(max_length=20)),
                ('locale_subcategory', models.CharField(blank=True, default='', max_length=30)),
                ('method', models.CharField(choices=[('direct', 'Direct NCES assignment'), ('overlay', 'Spatial overlay of NCES locale boundaries'), ('majority', 'Majority locale code from area-weighted overlay')], default='overlay', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urbanicity_facts', to='sw_warehouse.dimgeography')),
            ],
            options={
                'verbose_name': 'Urbanicity Fact',
                'db_table': 'sw_fact_urbanicity',
            },
        ),
        migrations.AddIndex(
            model_name='dimgeography',
            index=models.Index(fields=['summary_level', 'vintage_year'], name='sw_warehous_summary_26a994_idx'),
        ),
        migrations.AddIndex(
            model_name='dimgeography',
            index=models.Index(fields=['state_fips', 'summary_level'], name='sw_warehous_state_f_28dbe0_idx'),
        ),
        migrations.AddIndex(
            model_name='dimgeography',
            index=models.Index(fields=['is_current', 'summary_level'], name='sw_warehous_is_curr_563d50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimgeography',
            unique_together={('geoid', 'vintage_year')},
        ),
        migrations.AddIndex(
            model_name='factacsestimate',
            index=models.Index(fields=['geography', 'survey'], name='sw_fact_acs_geograp_158f14_idx'),
        ),
        migrations.AddIndex(
            model_name='factacsestimate',
            index=models.Index(fields=['variable', 'survey'], name='sw_fact_acs_variabl_aa7e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='factacsestimate',
            index=models.Index(fields=['reliability'], name='sw_fact_acs_reliabi_c41b31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factacsestimate',
            unique_together={('geography', 'variable', 'survey')},
        ),
        migrations.AddIndex(
            model_name='factdecennialcount',
            index=models.Index(fields=['geography', 'survey'], name='sw_fact_dec_geograp_9ff762_idx'),
        ),
        migrations.AddIndex(
            model_name='factdecennialcount',
            index=models.Index(fields=['variable', 'survey'], name='sw_fact_dec_variabl_ef2bad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factdecennialcount',
            unique_together={('geography', 'variable', 'survey')},
        ),
        migrations.AddIndex(
            model_name='factelectionresult',
            index=models.Index(fields=['geography', 'election_date', 'office'], name='sw_fact_ele_geograp_b4848b_idx'),
        ),
        migrations.AddIndex(
            model_name='factelectionresult',
            index=models.Index(fields=['office', 'party'], name='sw_fact_ele_office_ce79c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factelectionresult',
            unique_together={('geography', 'election_date', 'office', 'party', 'candidate_name')},
        ),
        migrations.AddIndex(
            model_name='factprecinctresult',
            index=models.Index(fields=['geography', 'election_date', 'office'], name='sw_fact_pre_geograp_c80d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='factprecinctresult',
            index=models.Index(fields=['office', 'party'], name='sw_fact_pre_office_0c056c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factprecinctresult',
            unique_together={('geography', 'election_date', 'office', 'party', 'candidate_name')},
        ),
        migrations.AddIndex(
            model_name='factredistrictingplan',
            index=models.Index(fields=['geography', 'cycle'], name='sw_fact_red_geograp_2606a4_idx'),
        ),
        migrations.AddIndex(
            model_name='factredistrictingplan',
            index=models.Index(fields=['cycle', 'chamber'], name='sw_fact_red_cycle_i_707e71_idx'),
        ),
        migrations.AddIndex(
            model_name='facturbanicity',
            index=models.Index(fields=['locale_code'], name='sw_fact_urb_locale__e45b67_idx'),
        ),
        migrations.AddIndex(
            model_name='facturbanicity',
            index=models.Index(fields=['locale_category'], name='sw_fact_urb_locale__d46ee2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facturbanicity',
            unique_together={('geography', 'nces_year', 'method')},
        ),
    ]
