# Generated by Django 6.0.5 on 2026-05-18 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimredistrictingcycle',
            name='decennial_census_year',
        ),
        migrations.RemoveField(
            model_name='dimtime',
            name='fiscal_year',
        ),
        migrations.AddField(
            model_name='dimredistrictingcycle',
            name='census_year',
            field=models.PositiveSmallIntegerField(default=0, help_text='Corresponding decennial Census year (typically equals cycle_year). 0 = unset.'),
        ),
        migrations.AddField(
            model_name='dimredistrictingcycle',
            name='effective_end',
            field=models.DateField(blank=True, help_text="End date of effective period (typically start of next cycle's effective period)", null=True),
        ),
        migrations.AddField(
            model_name='dimredistrictingcycle',
            name='effective_start',
            field=models.DateField(blank=True, help_text="Start date of this cycle's effective period (typically Jan 1 of first_election_year)", null=True),
        ),
        migrations.AddField(
            model_name='dimtime',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of calendar month (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='dimtime',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(default=0, help_text='Python weekday() convention: 0=Monday, 6=Sunday', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='dimtime',
            name='federal_fiscal_year',
            field=models.PositiveSmallIntegerField(default=0, help_text='Federal fiscal year (Oct-Sep). FY starts Oct 1 of (calendar_year - 1).'),
        ),
        migrations.AddField(
            model_name='dimtime',
            name='is_midterm_election',
            field=models.BooleanField(db_index=True, default=False, help_text='True on midterm general election day (every 4 years, offset from presidential)'),
        ),
        migrations.AddField(
            model_name='dimtime',
            name='is_presidential_election',
            field=models.BooleanField(db_index=True, default=False, help_text='True on presidential general election day (every 4 years)'),
        ),
        migrations.AddField(
            model_name='dimtime',
            name='week_of_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='ISO week number (1-53)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
        migrations.AlterField(
            model_name='dimredistrictingcycle',
            name='first_election_year',
            field=models.PositiveSmallIntegerField(default=0, help_text='First general election under this plan (typically cycle_year + 2). 0 = unset.'),
        ),
        migrations.AlterUniqueTogether(
            name='factredistrictingplan',
            unique_together={('geography', 'cycle', 'chamber', 'plan_type', 'district_number')},
        ),
    ]
