# Generated by Django 5.2.17 on 2026-09-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_events', '0002_event_canonicalization'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrativeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_event_type', models.CharField(choices=[('speech', 'Speech'), ('scandal', 'Scandal'), ('endorsement', 'Endorsement'), ('pac_formation', 'PAC Formation'), ('pledge_letter', 'Pledge Letter'), ('indictment', 'Indictment'), ('resignation', 'Resignation'), ('other', 'Other')], db_index=True, max_length=30)),
                ('duration_mode', models.CharField(choices=[('bounded', 'Bounded (fixed pre/post window)'), ('structural', 'Structural / Open-Ended')], db_index=True, default='bounded', max_length=20)),
                ('window_pre_days', models.PositiveIntegerField(blank=True, help_text='Bounded mode only: days before event.event_date the window opens', null=True)),
                ('window_post_days', models.PositiveIntegerField(blank=True, help_text='Bounded mode only: days after event.event_date the window closes', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Structural mode only. NULL = still in effect / open-ended; non-null = the date the regime this event opened was closed.', null=True)),
            ],
            options={
                'verbose_name': 'Narrative Event',
                'verbose_name_plural': 'Narrative Events',
                'db_table': 'sw_event_narrative',
            },
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='exposure_class',
            field=models.CharField(choices=[('public_actor', 'Public Actor'), ('incidental_private', 'Incidental Private')], db_index=True, default='public_actor', help_text='public_actor (default) chose their political exposure; incidental_private did not and requires sourcing_note justifying inclusion', max_length=20),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='sourcing_note',
            field=models.TextField(blank=True, default='', help_text='Required when exposure_class=incidental_private: why this private individual is named in this event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('corporate', 'Corporate Event'), ('spatiotemporal', 'Spatio-Temporal Event'), ('electoral', 'Electoral Event'), ('narrative', 'Narrative Event')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exposure_class', 'incidental_private'), _negated=True), ('sourcing_note__regex', '\\S'), _connector='OR'), name='ck_evpart_sourcing_note_required'),
        ),
        migrations.AddField(
            model_name='narrativeevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_detail', to='sw_events.event'),
        ),
        migrations.AddIndex(
            model_name='narrativeevent',
            index=models.Index(fields=['narrative_event_type'], name='idx_evnarr_type'),
        ),
        migrations.AddIndex(
            model_name='narrativeevent',
            index=models.Index(fields=['duration_mode'], name='idx_evnarr_duration_mode'),
        ),
        migrations.AddConstraint(
            model_name='narrativeevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_mode', 'bounded'), ('effective_to__isnull', True), models.Q(('window_post_days__isnull', True), ('window_pre_days__isnull', True), _negated=True)), models.Q(('duration_mode', 'structural'), ('window_post_days__isnull', True), ('window_pre_days__isnull', True)), _connector='OR'), name='ck_evnarr_duration_mode_fields'),
        ),
    ]
