# Generated by Django 5.2.17 on 2026-09-04 05:46
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('sw_events', '0003_narrative_event_exposure_class'),
    ]
    operations = [
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('precedes', 'Precedes'), ('relates_to', 'Relates To')], db_index=True, max_length=20)),
                ('sourcing_note', models.TextField(blank=True, default='', help_text="Required: the analyst's stated basis for this relationship claim. An edge with no justification is indistinguishable from a coincidental time-window overlap.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='sw_events.event')),
                ('target_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='sw_events.event')),
            ],
            options={
                'verbose_name': 'Event Link',
                'verbose_name_plural': 'Event Links',
                'db_table': 'sw_event_link',
                'indexes': [models.Index(fields=['source_event', 'edge_type'], name='idx_evlink_source_type'), models.Index(fields=['target_event', 'edge_type'], name='idx_evlink_target_type')],
                'constraints': [models.CheckConstraint(condition=models.Q(('edge_type__in', ['precedes', 'relates_to'])), name='ck_evlink_edge_type_valid'), models.CheckConstraint(condition=models.Q(('source_event', models.F('target_event')), _negated=True), name='ck_evlink_no_self_loop'), models.CheckConstraint(condition=models.Q(('sourcing_note__regex', '\\S')), name='ck_evlink_sourcing_note_required')],
                'unique_together': {('source_event', 'target_event', 'edge_type')},
            },
        ),
    ]
