# Generated by Django 5.2.15 on 2026-06-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(blank=True, db_index=True, default='', help_text='Source system identifier (e.g., targetsmart, tx_ethics, census_acs)', max_length=50)),
                ('jurisdiction_level', models.CharField(blank=True, default='', help_text='Jurisdiction level: federal, state, county, municipal', max_length=20)),
                ('jurisdiction_state', models.CharField(blank=True, default='', help_text='State abbreviation (if applicable)', max_length=2)),
                ('source_record_id', models.CharField(blank=True, default='', help_text='Original record ID from the source system', max_length=100)),
                ('ingested_at', models.DateTimeField(blank=True, help_text='When the record was ingested into SW', null=True)),
                ('entity_uuid', models.UUIDField(editable=False, help_text='Stable UUID. UUID5 for identity entities, UUID4 for artifacts. Immutable once assigned.', unique=True)),
                ('subtype', models.CharField(choices=[('person', 'Person'), ('committee', 'Committee'), ('organization', 'Organization')], db_index=True, help_text='Concrete agent kind; names the one-to-one detail accessor', max_length=20)),
                ('lifecycle_state', models.CharField(choices=[('active', 'Active'), ('dissolved', 'Dissolved'), ('merged', 'Merged into another agent'), ('unknown', 'Unknown')], db_index=True, default='active', help_text='active / dissolved / merged / unknown', max_length=20)),
                ('resolution_confidence', models.DecimalField(blank=True, decimal_places=4, help_text='Identity-resolution confidence in [0, 1]; NULL if not scored', max_digits=5, null=True)),
                ('dissolved_on', models.DateField(blank=True, help_text='Date the agent dissolved (NULL unless lifecycle_state is dissolved)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'sw_agent',
                'indexes': [models.Index(fields=['subtype', 'lifecycle_state'], name='idx_agent_subtype_state'), models.Index(fields=['data_source', 'source_record_id'], name='idx_agent_source_recid')],
            },
        ),
    ]
