# Generated by Django 5.2.15 on 2026-06-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_core', '0002_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(blank=True, db_index=True, default='', help_text='Source system identifier (e.g., targetsmart, tx_ethics, census_acs)', max_length=50)),
                ('jurisdiction_level', models.CharField(blank=True, default='', help_text='Jurisdiction level: federal, state, county, municipal', max_length=20)),
                ('jurisdiction_state', models.CharField(blank=True, default='', help_text='State abbreviation (if applicable)', max_length=2)),
                ('source_record_id', models.CharField(blank=True, default='', help_text='Original record ID from the source system', max_length=100)),
                ('ingested_at', models.DateTimeField(blank=True, help_text='When the record was ingested into SW', null=True)),
                ('entity_uuid', models.UUIDField(editable=False, help_text='Stable UUID. UUID5 for identity entities, UUID4 for artifacts. Immutable once assigned.', unique=True)),
                ('entity_id', models.UUIDField(db_index=True, help_text='entity_uuid of the attested entity (polymorphic target)')),
                ('entity_subtype', models.CharField(db_index=True, help_text='Kind of attested entity (agent, committee, event, filing, address, ...)', max_length=40)),
                ('attestation_kind', models.CharField(choices=[('fec', 'FEC claim'), ('entity_resolution', 'Entity resolution')], db_index=True, help_text='Subclass discriminator (fec, entity_resolution, ...)', max_length=40)),
                ('attested_values', models.JSONField(blank=True, default=dict, help_text='The attested data; shape varies per entity_subtype')),
                ('attested_values_hash', models.CharField(blank=True, db_index=True, default='', help_text='Content hash of attested_values for change detection', max_length=64)),
                ('attested_at', models.DateTimeField(blank=True, help_text='When the attestation was produced by its source', null=True)),
                ('attested_by', models.UUIDField(blank=True, help_text='Parser / operator / system that produced this attestation', null=True)),
                ('attestation_source_tier', models.CharField(choices=[('authoritative', 'Authoritative'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Authority tier of the source', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Ordering within (entity_id, entity_subtype), typically by attested_at')),
                ('is_canonical', models.BooleanField(default=False, help_text='True for the canonical-source-of-truth attestation per entity per kind')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
                'db_table': 'sw_attestation',
            },
        ),
        migrations.CreateModel(
            name='FECAttestation',
            fields=[
                ('attestation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_core.attestation')),
                ('source_artifact_hash', models.CharField(blank=True, db_index=True, default='', help_text='Content hash of the source artifact (e.g., the filing PDF)', max_length=64)),
                ('source_artifact_id', models.UUIDField(blank=True, help_text='Reference to the source artifact registry', null=True)),
                ('parser_version', models.CharField(blank=True, default='', help_text='Version of the parser that produced this attestation', max_length=40)),
                ('fec_form_type', models.CharField(blank=True, db_index=True, default='', help_text='FEC form_type from the source filing (F3, F3X, F1, ...)', max_length=20)),
                ('fec_form_version', models.CharField(blank=True, default='', help_text='FEC form version', max_length=20)),
            ],
            options={
                'verbose_name': 'FEC Attestation',
                'verbose_name_plural': 'FEC Attestations',
                'db_table': 'sw_fec_attestation',
            },
            bases=('sw_core.attestation',),
        ),
        migrations.AddIndex(
            model_name='attestation',
            index=models.Index(fields=['entity_id', 'entity_subtype'], name='idx_attest_entity'),
        ),
        migrations.AddIndex(
            model_name='attestation',
            index=models.Index(fields=['entity_subtype', 'attestation_kind'], name='idx_attest_subtype_kind'),
        ),
        migrations.AddIndex(
            model_name='attestation',
            index=models.Index(fields=['entity_id', 'entity_subtype', 'sequence'], name='idx_attest_entity_seq'),
        ),
        migrations.AddConstraint(
            model_name='attestation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_canonical', True)), fields=('entity_id', 'entity_subtype', 'attestation_kind'), name='uq_attestation_canonical_per_entity_kind'),
        ),
    ]
