"""Template-readiness G.2: setup wizard for a fresh clone.

Per G design (#211) Q1 = (b) manage.py template_init.

This is the "first-time setup wizard." After a fresh `git clone`,
running this command:

  1. Prompts (or accepts non-interactive args) for the target
     state(s) and a project-friendly name.
  2. Writes a .env file with sensible dev defaults.
  3. Runs migrations.
  4. (Optionally) runs seed_demo for the chosen states.

Usage:
    # Interactive
    python manage.py template_init

    # Non-interactive (suitable for CI / scripted setup)
    python manage.py template_init --non-interactive \\
        --states 48 --project-name myorg-warehouse

NOTE: This wizard does NOT rename the Django package directory
(`socialwarehouse/` -> `myproject/`). For almost all forkers, the
project-friendly identifier via `SW_PROJECT_NAME` env var (which
this wizard writes) is sufficient; the package directory stays
as `socialwarehouse/` so upstream merges keep working.

If you genuinely need a renamed Django package, see the
"Renaming the Django package (advanced)" section in
docs/quickstart.md — the rename recipe + trade-offs are
documented there.
"""

from pathlib import Path

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand


DEFAULT_ENV_TEMPLATE = """# Generated by `manage.py template_init` on {today}.
# Edit freely; this file is meant to be hand-edited as your project grows.

DJANGO_SECRET_KEY={secret_key}
DJANGO_DEBUG=True

POSTGRES_DB={db_name}
POSTGRES_USER={db_user}
POSTGRES_PASSWORD=
POSTGRES_HOST=localhost
POSTGRES_PORT=5432

SW_WAREHOUSE_ROOT=file:///tmp/sw-warehouse

# Optional: external API keys.
# CENSUS_API_KEY=
# BLS_API_KEY=

# Project-friendly identifier (informational; doesn't rename the Django package).
SW_PROJECT_NAME={project_name}

# Default seed states (used by seed_demo when --states is omitted).
SW_DEFAULT_STATES={default_states}
"""


class Command(BaseCommand):
    help = (
        "First-time setup wizard. Writes .env, runs migrations, "
        "optionally runs seed_demo for the chosen state(s)."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--non-interactive", action="store_true",
            help="Skip prompts; use --states / --project-name / --skip-seed flags.",
        )
        parser.add_argument(
            "--states", type=str, default="48",
            help="Comma-separated state FIPS for seed_demo. Default 48 (TX).",
        )
        parser.add_argument(
            "--project-name", type=str, default="socialwarehouse-dev",
            help="Project-friendly identifier (informational).",
        )
        parser.add_argument(
            "--db-name", type=str, default="socialwarehouse_dev",
            help="Postgres DB name to write to .env.",
        )
        parser.add_argument(
            "--db-user", type=str, default=None,
            help="Postgres user (defaults to $USER).",
        )
        parser.add_argument(
            "--skip-migrate", action="store_true",
            help="Don't run python manage.py migrate.",
        )
        parser.add_argument(
            "--skip-seed", action="store_true",
            help="Don't run seed_demo.",
        )

    def handle(self, *args, **options):
        from datetime import date
        import os
        import secrets

        interactive = not options["non_interactive"]

        # Resolve config — prompt if interactive, otherwise use flags.
        if interactive:
            self.stdout.write(self.style.SUCCESS(
                "=== SocialWarehouse template_init ==="
            ))
            project_name = self._prompt("Project name", options["project_name"])
            states = self._prompt("Seed state FIPS (comma-separated)", options["states"])
            db_name = self._prompt("Postgres DB name", options["db_name"])
            db_user = self._prompt("Postgres user", options["db_user"] or os.environ.get("USER", "postgres"))
            skip_seed = self._yes_no("Run seed_demo after migrate?", default_yes=True) is False
        else:
            project_name = options["project_name"]
            states = options["states"]
            db_name = options["db_name"]
            db_user = options["db_user"] or os.environ.get("USER", "postgres")
            skip_seed = options["skip_seed"]

        # 1. Write .env (next to manage.py).
        env_path = Path(settings.BASE_DIR) / ".env"
        if env_path.exists():
            self.stdout.write(self.style.WARNING(
                f".env already exists at {env_path}; skipping write (delete it first to regenerate)."
            ))
        else:
            env_text = DEFAULT_ENV_TEMPLATE.format(
                today=date.today().isoformat(),
                secret_key=secrets.token_urlsafe(50),
                db_name=db_name,
                db_user=db_user,
                project_name=project_name,
                default_states=states,
            )
            env_path.write_text(env_text)
            self.stdout.write(self.style.SUCCESS(f"Wrote {env_path}"))

        # 2. Migrate.
        if options["skip_migrate"]:
            self.stdout.write("Skipping migrate (--skip-migrate).")
        else:
            self.stdout.write("Running migrate…")
            try:
                call_command("migrate", verbosity=1)
            except Exception as exc:
                self.stdout.write(self.style.ERROR(
                    f"migrate failed: {exc}. Fix DB connection and re-run template_init."
                ))
                return

        # 3. Seed.
        if skip_seed:
            self.stdout.write("Skipping seed_demo (--skip-seed or interactive declined).")
        else:
            self.stdout.write(f"Running seed_demo --states={states}…")
            try:
                call_command("seed_demo", states=states)
            except Exception as exc:
                self.stdout.write(self.style.WARNING(
                    f"seed_demo encountered an error: {exc}. Partial data may be loaded; "
                    f"run `python manage.py seed_demo --states={states}` again later."
                ))

        # 4. Final guidance.
        self.stdout.write("")
        self.stdout.write(self.style.SUCCESS("template_init complete."))
        self.stdout.write(f"  Project: {project_name}")
        self.stdout.write(f"  Seeded states: {states}")
        self.stdout.write("")
        self.stdout.write("Next steps:")
        self.stdout.write("  1. Run `python manage.py createsuperuser` to set up admin access.")
        self.stdout.write("  2. Run `python manage.py runserver` and visit http://localhost:8000/.")
        self.stdout.write("")
        self.stdout.write("Note: SW_PROJECT_NAME in your .env is the project-friendly identifier;")
        self.stdout.write("the Django package directory stays as `socialwarehouse/` so upstream")
        self.stdout.write("merges keep working. If you genuinely need a renamed package, see the")
        self.stdout.write("`Renaming the Django package (advanced)` section in docs/quickstart.md.")

    def _prompt(self, question, default):
        try:
            response = input(f"{question} [{default}]: ").strip()
        except EOFError:
            response = ""
        return response or default

    def _yes_no(self, question, *, default_yes=True):
        prompt = "[Y/n]" if default_yes else "[y/N]"
        try:
            response = input(f"{question} {prompt}: ").strip().lower()
        except EOFError:
            response = ""
        if not response:
            return default_yes
        return response in ("y", "yes")
