"""Template instantiation helpers for ``swh init``.

Generates a ``.env`` file from sensible defaults, prompts for DB
credentials when running interactively, and writes the result next
to the repo root.
"""

from __future__ import annotations

import os
import secrets
from datetime import date
from pathlib import Path

ENV_TEMPLATE = """\
# Generated by `swh init` on {today}.
# Edit freely; this file is meant to be hand-edited as your project grows.

# --- PostgreSQL / PostGIS ---
POSTGRES_HOST={db_host}
POSTGRES_DB={db_name}
POSTGRES_USER={db_user}
POSTGRES_PASSWORD={db_password}
POSTGRES_HOST_AUTH_METHOD=scram-sha-256
POSTGRES_PORT={db_port}

# --- Docker build ---
UBUNTU_BASE_IMAGE=ubuntu:24.04
PYTHON_VENV_PATH=/opt/venv

# --- Spark ---
SPARK_NO_DAEMONIZE=true

# --- Django ---
DJANGO_SETTINGS_MODULE=socialwarehouse.settings.development
DJANGO_SECRET_KEY={secret_key}
DJANGO_DEBUG=True

# --- Celery ---
CELERY_BROKER_URL={redis_url}
CELERY_RESULT_BACKEND={redis_url}

# --- Neo4j ---
NEO4J_HEAP=512m
NEO4J_PAGECACHE=512m
NEO4J_PASSWORD=CHANGEME

# --- SedonaDB ---
SEDONADB_PORT=8889

# --- Census data ---
CENSUS_YEAR=2023
CENSUS_CONGRESS_NUMBER=118
CENSUS_STATES=all

# --- Project ---
SW_PROJECT_NAME={project_name}
SW_DEFAULT_STATES={default_states}
SW_WAREHOUSE_ROOT=file:///tmp/sw-warehouse

# Optional: external API keys.
# CENSUS_API_KEY=
# BLS_API_KEY=
"""


def generate_env(
    *,
    project_name: str = "socialwarehouse-dev",
    db_name: str = "socialwarehouse_dev",
    db_user: str | None = None,
    db_password: str = "",
    db_host: str = "localhost",
    db_port: int = 5432,
    redis_url: str = "redis://redis:6379/0",
    default_states: str = "48",
) -> str:
    """Return a rendered ``.env`` file body."""
    return ENV_TEMPLATE.format(
        today=date.today().isoformat(),
        secret_key=secrets.token_urlsafe(50),
        project_name=project_name,
        db_name=db_name,
        db_user=db_user or os.environ.get("USER", "postgres"),
        db_password=db_password,
        db_host=db_host,
        db_port=db_port,
        redis_url=redis_url,
        default_states=default_states,
    )


def find_repo_root() -> Path:
    """Walk up from CWD to find the repo root (contains pyproject.toml)."""
    cwd = Path.cwd()
    for parent in [cwd, *cwd.parents]:
        if (parent / "pyproject.toml").exists():
            return parent
    return cwd
